<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:ns0="http://TargetNamespace.com/ArtistEnricherAPIReference_GetArtistDetails_response"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="aced.cloud.demo"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://xmlns.oracle.com/ProposedActsService/NewActProposalsServices/ArtistEnricherAPIReference"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/ArtistEnricherAPIReference.wsdl"/>
                <oracle-xsl-mapper:rootElement name="artist"
                                               namespace="http://TargetNamespace.com/ArtistEnricherAPIReference_GetArtistDetails_response"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/ArtistsService.wsdl"/>
                <oracle-xsl-mapper:rootElement name="findArtistResponseMessage" namespace="aced.cloud.demo"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT MAR 04 06:59:35 CET 2017].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:findArtistResponseMessage>
            <tns:spotifyId>
                <xsl:value-of select="/ns0:artist/ns0:spotifyId"/>
            </tns:spotifyId>
            <tns:biography>
                <xsl:value-of select="/ns0:artist/ns0:biography"/>
            </tns:biography>
            <tns:name>
                <xsl:value-of select="/ns0:artist/ns0:name"/>
            </tns:name>
            <tns:genres>
                <xsl:value-of select="/ns0:artist/ns0:genres"/>
            </tns:genres>
            <tns:imageURL>
                <xsl:value-of select="/ns0:artist/ns0:imageURL"/>
            </tns:imageURL>
            <tns:spottiyHRef>
                <xsl:value-of select="/ns0:artist/ns0:spottiyHRef"/>
            </tns:spottiyHRef>
            <xsl:for-each select="/ns0:artist/ns0:albums">
                <tns:albums>
                    <tns:title>
                        <xsl:value-of select="ns0:title"/>
                    </tns:title>
                    <tns:imageURL>
                        <xsl:value-of select="ns0:imageURL"/>
                    </tns:imageURL>
                    <tns:spotifyId>
                        <xsl:value-of select="ns0:spotifyId"/>
                    </tns:spotifyId>
                    <tns:releaseDate>
                        <xsl:value-of select="ns0:releaseDate"/>
                    </tns:releaseDate>
                </tns:albums>
            </xsl:for-each>
        </tns:findArtistResponseMessage>
    </xsl:template>
</xsl:stylesheet>
