<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="aced.cloud.demo"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/NewActProposalsService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="submitActProposalRequestMessage" namespace="aced.cloud.demo"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/NewActProposalsServiceWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="submitActProposalRequestMessage" namespace="aced.cloud.demo"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU SEP 07 15:50:04 CEST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:submitActProposalRequestMessage>
      <ns0:name>
        <xsl:value-of select="/ns0:submitActProposalRequestMessage/ns0:name"/>
      </ns0:name>
      <ns0:numberOfVotes>
        <xsl:value-of select="/ns0:submitActProposalRequestMessage/ns0:numberOfVotes"/>
      </ns0:numberOfVotes>
      <ns0:description>
        <xsl:value-of select="/ns0:submitActProposalRequestMessage/ns0:description"/>
      </ns0:description>
      <xsl:if test="/ns0:submitActProposalRequestMessage/ns0:imageURL">
        <ns0:imageURL>
          <xsl:value-of select="/ns0:submitActProposalRequestMessage/ns0:imageURL"/>
        </ns0:imageURL>
      </xsl:if>
      <xsl:if test="/ns0:submitActProposalRequestMessage/ns0:image">
        <ns0:image>
          <xsl:value-of select="/ns0:submitActProposalRequestMessage/ns0:image"/>
        </ns0:image>
      </xsl:if>
    </ns0:submitActProposalRequestMessage>
  </xsl:template>
</xsl:stylesheet>
