<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/RetrieveProposedActDetails"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="aced.cloud.demo"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/ProposedActsService/ProposedActsService/RetrieveProposedActDetails"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/RetrieveProposedActDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ProposedActsCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/RetrieveProposedActDetails"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ProposedActsService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="getProposedActDetailsResponseMessage" namespace="aced.cloud.demo"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT FEB 20 06:46:54 CET 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:getProposedActDetailsResponseMessage>
      <tns:proposedActDetails>
        <tns:id>
          <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:id"/>
        </tns:id>
        <tns:name>
          <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:name"/>
        </tns:name>
        <tns:numberOfVotes>
          <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:numberOfVotes"/>
        </tns:numberOfVotes>
        <tns:description>
          <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:description"/>
        </tns:description>
        <xsl:if test="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:genres">
          <tns:genres>
            <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:genres"/>
          </tns:genres>
        </xsl:if>
        <tns:biography>
          <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:biography"/>
        </tns:biography>
        <xsl:if test="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:imageUrl">
          <tns:imageURL>
            <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:imageUrl"/>
          </tns:imageURL>
        </xsl:if>
        <xsl:if test="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:image">
          <tns:image>
            <xsl:value-of select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:image"/>
          </tns:image>
        </xsl:if>
        <tns:discography>
          <xsl:for-each select="/ns0:ProposedActsCollection/ns0:ProposedActs/ns0:actAlbumsCollection/ns0:ActAlbums">
            <xsl:if test=".">
              <tns:album>
                <tns:title>
                  <xsl:value-of select="ns0:title"/>
                </tns:title>
                <tns:year>
                  <xsl:value-of select="xp20:year-from-dateTime (ns0:releaseDate )"/>
                </tns:year>
                <xsl:if test="ns0:coverimageurl">
                  <tns:coverImageUrl>
                    <xsl:value-of select="ns0:coverimageurl"/>
                  </tns:coverImageUrl>
                </xsl:if>
              </tns:album>
            </xsl:if>
          </xsl:for-each>
        </tns:discography>
      </tns:proposedActDetails>
    </tns:getProposedActDetailsResponseMessage>
  </xsl:template>
</xsl:stylesheet>
