<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/retrieveDetailsForAct" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="aced.cloud.demo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ProposedActsService/ProposedActsService/retrieveDetailsForAct"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/retrieveDetailsForAct.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/retrieveDetailsForAct"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ProposedActsService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="getProposedActDetailsRequestMessage" namespace="aced.cloud.demo"/>
            <oracle-xsl-mapper:param name="initial.part1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ProposedActsService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="getProposedActDetailsResponseMessage" namespace="aced.cloud.demo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE SEP 26 17:54:07 PDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initial.part1"/>
   <xsl:template match="/">
      <ns1:getProposedActDetailsResponseMessage>
         <ns1:proposedActDetails>
            <ns1:id>
               <xsl:value-of select="$initial.part1/ns1:getProposedActDetailsRequestMessage/ns1:proposedActId"/>
            </ns1:id>
            <ns1:name>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:NAME"/>
            </ns1:name>
            <ns1:legalName>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:LEGAL_NAME"/>
            </ns1:legalName>
            <ns1:country>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:COUNTRY_OF_ORIGIN"/>
            </ns1:country>
            <ns1:era>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:ERA"/>
            </ns1:era>
            <ns1:artistType>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:ARTIST_TYPE"/>
            </ns1:artistType>
            <ns1:primaryGenre>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:GENRE"/>
            </ns1:primaryGenre>
            <ns1:popularity>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:POPULARITY"/>
            </ns1:popularity>
            <ns1:genres>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:GENRES"/>
            </ns1:genres>
            <ns1:biography>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:BIOGRAPHY"/>
            </ns1:biography>
            <ns1:imageURL>
               <xsl:value-of select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:IMAGE_URL"/>
            </ns1:imageURL>
            <ns1:discography>
               <xsl:for-each select="/ns0:OutputParameters/ns0:GET_ACT_DETAILS/ns0:ALBUMS/ns0:ALBUMS_ITEM">
                  <ns1:album>
                     <ns1:title>
                        <xsl:value-of select="ns0:TITLE"/>
                     </ns1:title>
                     <ns1:year>
                        <xsl:value-of select="xp20:year-from-dateTime (ns0:RELEASE_DATE )"/>
                     </ns1:year>
                     <ns1:coverImageUrl>
                        <xsl:value-of select="ns0:COVER_IMAGE_URL"/>
                     </ns1:coverImageUrl>
                     <xsl:if test="ns0:GENRE">
                        <ns1:genre>
                           <xsl:value-of select="ns0:GENRE"/>
                        </ns1:genre>
                     </xsl:if>
                     <ns1:trackCount>
                        <xsl:value-of select="ns0:TRACK_COUNT"/>
                     </ns1:trackCount>
                  </ns1:album>
               </xsl:for-each>
            </ns1:discography>
         </ns1:proposedActDetails>
      </ns1:getProposedActDetailsResponseMessage>
   </xsl:template>
</xsl:stylesheet>
