FORMAT: 1A
HOST: http://apics.oracle.com:8001
URL: http://apics.oracle.com:8001/OfmAcedemoActsApi

# OfmAcedemoActsApi

API for requesting all needed information about act proposals already available.

## Rate Limit

This API is limited to twenty requests per second per application. Requests exceeding this threshold are rejected.

## Get Proposed Acts [/OfmAcedemoActsApi/proposedacts{?mininumNumberOfVotes}{?maxNumberOfProposals}{?addedSince}]

### Get Proposed Acts [GET]

Gets all proposed acts with some meta information.

+ Parameters
    + mininumNumberOfVotes (required, integer, `10`) ... Filter criterium tha defines the minimum number of votes an act should have.
    + maxNumberOfProposals (optional, integer, `100`) ... Filter criterium that defines the maximum number of proposals an act should. have
    + addedSince (optional, date, `2017-03-10`) ... Filter criterium that defines the minimim date of an proposals submission. 
    
+ Request 

    + Headers
        
            Authorization: Basic authentication information
            api-key:Key retrieved from APIP CS while registering for API
            tenant-id: The current tenant-id (Ask your provider)
    

+ Response 200 (application/json)

        {
          "proposedActs": {
            "ProposedActSummary": [
              {
                "id": 21,
                "name": "john denver",
                "numberOfVotes": 45,
                "registrationDate": "2017-03-15T07:48:05.063757+00:00"
              },
              {
                "id": 70,
                "name": "Rita Coolidge",
                "numberOfVotes": 15,
                "registrationDate": "2017-03-19T05:39:14.481048+00:00"
              }
            ]
          }
        }

+ Response 400 (text/plain)

        Request doesn't conatin all header information (tenant-id).
        
+ Response 401 (text/plain)

        Request doesn't contain valid authentication information.
        
+ Response 403 (text/plain)

        Request doesn't cotain valid API Key.

## Get Proposed Act Details [/OfmAcedemoActsApi{?proposedActId}]

### Get Proposed Act Details [GET]

Get detail information for a specific act.

+ Parameters
    + proposedActId (required, integer, `21`) ... Defines the ID of the act for which the detail information should be retrieved.
    
+ Request 

    + Headers
        
            Authorization: Basic authentication information
            api-key:Key retrieved from APIP CS while registering for API
            tenant-id: The current tenant-id (Ask your provider)
            
+ Response 200 (application/xml)

        {
          "proposedActDetails": {
            "id": 21,
            "name": "john denver",
            "numberOfVotes": 45,
            "description": "The Country Boy. Unfortunately: he is dead",
            "genres": "[\"adult standards\",\"christmas\",\"country christmas\",\"folk\",\"folk christmas\",\"folk rock\",\"mellow gold\",\"singer-songwriter\",\"soft rock\",\"traditional country\",\"traditional folk\"]",
            "biography": "To Be Provided",
            "imageURL": "https://i.scdn.co/image/20231471bcc579479dac4c8f6218182cf0aa16a9",
            "image": null,
            "discography": {
              "album": [
                {
                  "title": "The Classic Christmas Album",
                  "year": 2012,
                  "coverImageUrl": "https://i.scdn.co/image/d52ad1ce5441d7d1473462eaf814d37c2fe93c9c"
                },
                {
                  "title": "Live At Cedar Rapids - 12/10/87",
                  "year": 2011,
                  "coverImageUrl": "https://i.scdn.co/image/9b147bb6da1ea54b3181f88b670477bb697d98c3"
                },
                {
                  "title": "Windsong",
                  "year": 1975,
                  "coverImageUrl": "https://i.scdn.co/image/32c1eb751db1d180977f953280ce068361dae458"
                }
              ]
            }
          }
        }
        
+ Response 400 (text/plain)

        Request doesn't conatin all header information (tenant-id).
        
+ Response 401 (text/plain)

        Request doesn't contain valid authentication information.
        
+ Response 403 (text/plain)

        Request doesn't cotain valid API Key.